/**
 * Field-level zod schemas shared by every action input (client forms and the server re-check).
 * Structural validation only: business rules that need stored state (dates vs. today/tracking start,
 * refund limits, allocations) are enforced by the server services.
 */
import { z } from "zod";

import {
  AMOUNT_ERROR_MESSAGES,
  CURRENCIES,
  MAX_SUPPORTED_YEAR,
  MIN_SUPPORTED_YEAR,
  parseAmount,
  parseLocalDate,
  type LocalDate,
  type Minor,
} from "@/domain";

import { TEXT_LIMITS, type TextLimitField } from "./limits";

/** Largest value of a Postgres `integer` (version counters). */
const MAX_INT4 = 2_147_483_647;

/** Characters that are never allowed: C0 controls (newline optionally), DEL and C1 controls. */
function hasControlCharacters(text: string, allowNewline: boolean): boolean {
  for (let i = 0; i < text.length; i += 1) {
    const code = text.charCodeAt(i);
    if (code === 0x0a && allowNewline) continue;
    if (code < 0x20 || (code >= 0x7f && code <= 0x9f)) return true;
  }
  return false;
}

/** Trims, normalises to NFC and (for multi-line text) converts CRLF / CR line endings to LF. */
function normalizeText(raw: string, multiline: boolean): string {
  const unified = multiline ? raw.replace(/\r\n?/g, "\n") : raw;
  return unified.normalize("NFC").trim();
}

interface TextOptions {
  field: TextLimitField;
  /** Human label used in messages, e.g. "Source". */
  label: string;
  multiline?: boolean;
}

function checkText(value: string, opts: TextOptions, ctx: z.RefinementCtx): boolean {
  const max = TEXT_LIMITS[opts.field];
  if (value.length > max) {
    ctx.addIssue({ code: "custom", message: `${opts.label} can be at most ${max} characters.` });
    return false;
  }
  if (hasControlCharacters(value, opts.multiline === true)) {
    ctx.addIssue({
      code: "custom",
      message: opts.multiline
        ? `${opts.label} can't contain control characters (line breaks are fine).`
        : `${opts.label} can't contain line breaks or control characters.`,
    });
    return false;
  }
  return true;
}

/** Required text: trimmed, non-empty, length-limited, no control characters. */
export function requiredText(opts: TextOptions) {
  return z.string({ error: `Enter ${opts.label.toLowerCase()}.` }).transform((raw, ctx): string => {
    const value = normalizeText(raw, opts.multiline === true);
    if (value === "") {
      ctx.addIssue({ code: "custom", message: `Enter ${opts.label.toLowerCase()}.` });
      return z.NEVER;
    }
    return checkText(value, opts, ctx) ? value : z.NEVER;
  });
}

/** Optional text: missing, null or blank becomes null; otherwise trimmed and checked like required text. */
export function optionalText(opts: TextOptions) {
  return z
    .string({ error: `${opts.label} must be text.` })
    .nullish()
    .transform((raw, ctx): string | null => {
      if (raw === null || raw === undefined) return null;
      const value = normalizeText(raw, opts.multiline === true);
      if (value === "") return null;
      return checkText(value, opts, ctx) ? value : z.NEVER;
    });
}

/** A user-typed amount parsed strictly by the domain parser into integer minor units. */
export const amountField = z
  .string({ error: AMOUNT_ERROR_MESSAGES.empty })
  .transform((raw, ctx): Minor => {
    const parsed = parseAmount(raw);
    if (!parsed.ok) {
      ctx.addIssue({ code: "custom", message: AMOUNT_ERROR_MESSAGES[parsed.error] });
      return z.NEVER;
    }
    return parsed.minor;
  });

/** A local calendar date `YYYY-MM-DD` (real date, supported year range). */
export const localDateField = z
  .string({ error: "Enter a date." })
  .transform((raw, ctx): LocalDate => {
    const parsed = parseLocalDate(raw.trim());
    if (parsed === null) {
      ctx.addIssue({
        code: "custom",
        message: `Enter a real date between ${MIN_SUPPORTED_YEAR} and ${MAX_SUPPORTED_YEAR} (YYYY-MM-DD).`,
      });
      return z.NEVER;
    }
    return parsed;
  });

export const currencyField = z.enum(CURRENCIES, { error: "Choose CAD or USD." });

/** One UUID per form instance, generated by the client and regenerated only after a confirmed success. */
export const idempotencyKeyField = z.uuid({ error: "This form is out of date. Reload the page and try again." });

export const recordIdField = z.uuid({ error: "That record could not be found." });

export const expectedVersionField = z
  .number({ error: "This form is out of date. Reload the page and try again." })
  .int()
  .min(1)
  .max(MAX_INT4);

export const bucketYearField = z
  .number({ error: "Choose a period." })
  .int({ error: "Choose a period." })
  .min(MIN_SUPPORTED_YEAR, { error: "Choose a period." })
  .max(MAX_SUPPORTED_YEAR, { error: "Choose a period." });

/** Strict boolean (checkbox) — no string coercion. */
export const checkboxField = z.boolean({ error: "Choose yes or no." });
